sudo: required
dist: trusty
language: c
cache: ccache
services: docker

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
            - lcov
      env:
        - CXX=g++-4.9 CC=gcc-4.9 MODE=Debug COVERAGE=TRUE
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
      env:
        - CXX=clang++-3.6 CC=clang-3.6 MODE=Debug
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
      env:
        - CXX=g++-4.9 CC=gcc-4.9 MODE=Release
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
            - valgrind
      env:
        - CXX=clang++-3.6 CC=clang-3.6 MODE=Release

    # Xcode 7.3 (clang)
    - os: osx
      compiler: clang
      env: CXX=clang++ CC=clang MODE=Debug
      osx_image: xcode7.3

    - os: osx
      compiler: clang
      env: CXX=clang++ CC=clang MODE=Release
      osx_image: xcode7.3

install:
  - pip install --user pyyaml
  - pip install --user poster

script:
  - set -e
  - export NOCACHE_LOCAL=TRUE
  - export NOCACHE_REMOTE=FALSE
  # - ./build 'boost*' --server=http://artifacts.myftp.biz:8080
  # - ./build 'boost-headers' --server=http://artifacts.myftp.biz:8080 -o
  # - ./build 'python' --server=http://artifacts.myftp.biz:8080 -o --no-purge
  # - ./build 'python' --server=http://artifacts.myftp.biz:8080 -o --only-packing -d
  # - ./build 'boost-python' --server=http://artifacts.myftp.biz:8080 -d -o
  # - ./build spdlog --server=http://artifacts.myftp.biz:8080 -d
  # - ./build google-gmock --server=http://artifacts.myftp.biz:8080
  # - ./build raknet --server=http://artifacts.myftp.biz:8080
  # - ./build intel-tbb* -o --server=http://artifacts.myftp.biz:8080
  # - ./build cryptopp -o --server=http://artifacts.myftp.biz:8080
  # - ./build paho-mqtt3 -o --server=http://artifacts.myftp.biz:8080
  # - ./build paho-mqttpp3 -o --server=http://artifacts.myftp.biz:8080
  # no esta compilando
  - ./build json -o --server=http://artifacts.myftp.biz:8080 -d
  - set +e
