sudo: required
dist: trusty
language: c
services: docker

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
            - lcov
      env:
        - CXX=g++-4.9 CC=gcc-4.9 MODE=Debug COVERAGE=TRUE
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
      env:
        - CXX=clang++-3.6 CC=clang-3.6 MODE=Debug
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
      env:
        - CXX=g++-4.9 CC=gcc-4.9 MODE=Release
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
            - valgrind
      env:
        - CXX=clang++-3.6 CC=clang-3.6 MODE=Release

    - os: osx
      compiler: clang
      env: CXX=clang++ CC=clang MODE=Debug
      osx_image: xcode7.3

    - os: osx
      compiler: clang
      env: CXX=clang++ CC=clang MODE=Release
      osx_image: xcode7.3

install:
  - pip install --user pyyaml
  - pip install --user poster

script:
  - set -e
  - CMAKI_PWD=$(pwd) CMAKI_INSTALL=$(pwd)/bin npm install
  - CMAKI_PWD=$(pwd) CMAKI_INSTALL=$(pwd)/bin ./build boost-system --server=http://artifacts.myftp.biz:8080
  - set +e
