sudo: required
dist: trusty
language: c
cache: ccache
services: docker

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
            - lcov
      env:
        - CXX=g++-4.9 CC=gcc-4.9 MODE=Debug COVERAGE=TRUE
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
      env:
        - CXX=clang++-3.6 CC=clang-3.6 MODE=Debug
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
      env:
        - CXX=g++-4.9 CC=gcc-4.9 MODE=Release
    - os: linux
      compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
            - valgrind
      env:
        - CXX=clang++-3.6 CC=clang-3.6 MODE=Release

    - os: osx
      compiler: clang
      env: CXX=clang++ CC=clang MODE=Debug
      osx_image: xcode7.3
      # osx_image: xcode8

    - os: osx
      compiler: clang
      env: CXX=clang++ CC=clang MODE=Release
      osx_image: xcode7.3
      # osx_image: xcode8

install:
  - pip install --user pyyaml
  - pip install --user poster

script:
  - set -e
  - curl -s https://raw.githubusercontent.com/makiolo/cmaki/master/bootstrap.sh | bash
  - export NOCACHE_LOCAL=TRUE
  - export NOCACHE_REMOTE=FALSE
  - export USE_CMAKI_IDENTIFIER=TRUE
  - export CMAKI_PWD=$(pwd)
  - export CMAKI_IDENTIFIER_FOLDER=$CMAKI_PWD/cmaki_identifier
  - git clone https://github.com/makiolo/cmaki_identifier.git $CMAKI_IDENTIFIER_FOLDER
  - cd $CMAKI_IDENTIFIER_FOLDER
  - CMAKI_PWD=$(pwd) CMAKI_INSTALL=$CMAKI_IDENTIFIER_FOLDER/../output/3rdparties/cmaki/ci npm install
  - CMAKI_PWD=$(pwd) CMAKI_INSTALL=$CMAKI_IDENTIFIER_FOLDER/../cmaki/ci npm install
  - cd -
  - echo find $CMAKI_PWD/output/3rdparties/cmaki/ci
  - find $CMAKI_PWD/output/3rdparties/cmaki/ci
  - find $CMAKI_PWD/cmaki/ci
  - echo ------------------
  - $CMAKI_PWD/output/3rdparties/cmaki/ci/$MODE/predef
  - $CMAKI_PWD/cmaki/ci/$MODE/predef
  - echo ------------------
  # - ./build boost-headers -o --server=http://artifacts.myftp.biz:8080
  # - ./build boost-context -o --server=http://artifacts.myftp.biz:8080 -d
  # - ./build boost-system --server=http://artifacts.myftp.biz:8080
  # - ./build 'boost*' --server=http://artifacts.myftp.biz:8080
  # - ./build 'boost-headers' --server=http://artifacts.myftp.biz:8080 -o
  # - ./build boost-coroutine2 boost-filesystem --server=http://artifacts.myftp.biz:8080
  # - ./build 'python' --server=http://artifacts.myftp.biz:8080 -o --no-purge
  # - ./build 'boost-python' --server=http://artifacts.myftp.biz:8080
  # - ./build spdlog --server=http://artifacts.myftp.biz:8080 -d
  # - ./build google-gmock --server=http://artifacts.myftp.biz:8080 -d
  # - ./build raknet -o --server=http://artifacts.myftp.biz:8080
  # - ./build intel-tbb* -o --server=http://artifacts.myftp.biz:8080
  # - ./build cryptopp -o --server=http://artifacts.myftp.biz:8080
  # - ./build paho-mqtt3 -o --server=http://artifacts.myftp.biz:8080
  # - ./build paho-mqttpp3 -o --server=http://artifacts.myftp.biz:8080
  - ./build json -o --server=http://artifacts.myftp.biz:8080 -d
  # no compila / no se
  # - ./build shiny --server=http://artifacts.myftp.biz:8080 -d
  - set +e
