sudo: required
dist: trusty

language: c
cache: ccache

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
      env:
        - CXX=g++-4.9 CC=gcc-4.9 MODE=Debug
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
      env:
        - CXX=clang++-3.6 CC=clang-3.6 MODE=Debug
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - cmake
            - g++-4.9
      env:
        - CXX=g++-4.9 CC=gcc-4.9 MODE=Release
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - cmake
            - clang-3.6
      env:
        - CXX=clang++-3.6 CC=clang-3.6 MODE=Release

install:
  - pip install --user pyyaml
  - pip install --user poster

script:
  - set -e
  - export NOCACHE_LOCAL=TRUE
  - export NOCACHE_REMOTE=FALSE
  # build in travis 7-feb
  #- ./build 'boost*' --server=http://artifacts.myftp.biz:8080
  #- ./build spdlog --server=http://artifacts.myftp.biz:8080
  #- ./build raknet google-gmock --server=http://artifacts.myftp.biz:8080
  #- ./build raknet --server=http://artifacts.myftp.biz:8080
  #- ./build intel-tbb* -o --server=http://artifacts.myftp.biz:8080
  - ./build cryptopp -o --server=http://artifacts.myftp.biz:8080
  - set +e
